_BASE_: ../../vita/youtubevis_2021/vita_SWIN_bs8.yaml
MODEL:
  META_ARCHITECTURE: "Genvis"
  WEIGHTS: "vita_swin_ytvis2021.pth"
  VITA:
    ENC_WINDOW_SIZE: 0
    FREEZE_DETECTOR: True
  GENVIS:
    LEN_CLIP_WINDOW: 3
DATASETS:
  DATASET_RATIO: [1.0, 0.75]
  TRAIN: ("coco2ytvis2021_train", "ytvis_2021_train")
  TEST: ("ytvis_2021_val",)
SOLVER:
  IMS_PER_BATCH: 8
  STEPS: (50000,)
  MAX_ITER: 90000
  CHECKPOINT_PERIOD: 5000
INPUT:
  SAMPLING_FRAME_NUM: 15 # 5 clips
  SAMPLING_FRAME_RANGE: 12
  SAMPLING_FRAME_SHUFFLE: False
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 8
TEST:
  EVAL_PERIOD: 0
  DETECTIONS_PER_IMAGE: 10