_BASE_: ../../vita/ovis/vita_SWIN_bs8.yaml
MODEL:
  META_ARCHITECTURE: "Genvis"
  WEIGHTS: "vita_swin_ovis.pth"
  VITA:
    ENC_WINDOW_SIZE: 0
    FREEZE_DETECTOR: True
  GENVIS:
    LEN_CLIP_WINDOW: 3
DATASETS:
  DATASET_RATIO: [1.0, 0.25]
  TRAIN: ("coco2ovis_train", "ovis_train")
  TEST: ("ovis_val",)
SOLVER:
  IMS_PER_BATCH: 8
  STEPS: (100000,)
  MAX_ITER: 140000
  CHECKPOINT_PERIOD: 5000
INPUT:
  SAMPLING_FRAME_NUM: 15 # 5 clips
  SAMPLING_FRAME_RANGE: 12
  SAMPLING_FRAME_SHUFFLE: False
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 8
TEST:
  EVAL_PERIOD: 0
  DETECTIONS_PER_IMAGE: 20
